<?php
/**
 *
 *  Copyright (C) 2017 paj@gaiterjones.com
 *
 *
 */

namespace PAJ\Application\AmazonDev\Alexa\Intent;

/**
 * ALEXA INTENT DATA CLASS
 *
 */
class CleverStuffData {

	// "clever" quotes https://www.witty-quotes.com/Clever-quotes/
	//
	static function cleverQuotes()
	{
		return array(
			"Cole's Axiom: The sum of intelligence on the planet is a constant. The population is growing",
			"Nothing is illegal until you get caught.",
			"You cannot achieve the impossible without attempting the absurd.",
			"Age is an issue of mind over matter. If you don't mind, it doesn't matter.",
			"When bosses talk about improving productivity, they are never talking about themselves.",
			"Make it idiot proof and someone will make a better idiot.",
			"I doubt, therefore I might be.",
			"It is far more impressive when others discover your good qualities without your help.",
			"Accept risk. Accept responsibility. Put a lawyer out of business.",
			"If you love something very much, give it away. If it comes back to you, it's yours forever. If it doesn't, it wasn't yours to begin with.",
			"The reason grandparents and grandchildren get along so well is that they have a common enemy.",
			"Amateurs built the ark. Professionals built the Titanic.",
			"In the end, it's not the years in your life that count, it's the life in your years.",
			"Love isn't only blind, it's also deaf, dumb, and stupid.",
			"Unless you can question your own beliefs, you have no place questioning the beliefs of others.",
			"Those who drink to drown their sorrows should be told that sorrows know how to swim",
			"Once the toothpaste is out of the tube, it's hard to get it back in.",
			"A great many people think they are thinking when they are merely rearranging their prejudices.",
			"A real person has two reasons for doing anything, a good reason, and the real reason.",
			"Age is a very high price to pay for maturity.",
			"Never put off till tomorrow what you can avoid all together.",
			"When tempted to fight fire with fire, keep in mind that the Fire Department usually uses water.",
			"My opinions may have changed, but not the fact that I am right.",
			"Incoming fire has the right of way.",
			"Give the gift of love, and people think you're cheap. Give them a cheap bit of crap, and they love you for it. Go figure.",
			"Please excuse my bad English; I'm American.",
			"There is a light at the end of every tunnel. Just pray that it isnt a train.",
			"People who say it can't be done, should not interrupt those of us who are doing it.",
			"If you can't learn to do it well, learn to enjoy doing it badly.",
			"Things are only impossible until they're not.",
			"A rich man is nothing but a poor man with money",
			"Whoever said money can't buy happiness simply didn't know where to go shopping.",
			"Keep that sense of humor; it's critical.",
			"Don't let schooling get in the way of your education.",
			"Ever notice that the people who are late are often much jollier than the people who have to wait for them?",
			"Only adults have difficulty with childproof caps.",
			"Plagiarism is copying from one source; research is copying from many.",
			"I would never die for my beliefs because I might be wrong.",
			"If advertisers spent the same amount of money on improving their products as they do on advertising then they wouldn't have to advertise them.",
			"There's an old proverb that says just about whatever you want it to.",
			"I judge a religion as being good or bad based on whether its adherents become better people as a result of practicing it.",
			"Under capitalism, man exploits man. Under communism, it's just the opposite.",
			"Warning: Dates in Calendar are closer than they appear.",
			"The intelligence of a group is inversely proportionate to its size",
			"To argue with a person who has renounced the use of reason is like administering medicine to the dead.",
			"Life may have no meaning. Or even worse, it may have a meaning of which I disapprove.",
			"The two most common things in the Universe are hydrogen and stupidity.",
			"Those who can make you believe absurdities can make you commit atrocities.",
			"A free society is one where it is safe to be unpopular.",
			"Experience is that marvelous thing that enables you to recognize a mistake when you make it again.",
			"An encyclopedia is a system for collecting dust in alphabetical order.",
			"The worst part of having success is trying to find someone who is happy for you.",
			"Life would be much simpler and things would get done much faster if it weren't for other people.",
			"Technology is dominated by two types of people: Those who understand what they do not manage. Those who manage what they do not understand.",
			"Doubt isn't the opposite of faith; it is an element of faith.",
			"A penny saved is a penny taxed.",
			"Anytime things appear to be going better, you have overlooked something.",
			"It's not what you say in your argument, it's how loud you say it.",
			"If it jams, force it. If it breaks, it needed replacing anyway.",
			"No one is perfect, but some of us are closer than others.",
			"I AM, therefore I THINK!",
			"Life isn't weird; it's the people in it.",
			"A celebrity is a person who is known for his well-knownness.",
			"In case of doubt, make it sound convincing.",
			"It would be nice to be sure of anything the way some people are of everything.",
			"The early bird who catches the worm works for someone who comes in late and owns the worm farm.",
			"There is not much to choose between a woman who deceives us for another, and a woman who deceives another for ourselves.",
			"The difference between a drunk and a alcoholic is that a drunk doesn't have to attend all those meetings.",
			"nothing brings people closer than a common enemy",
			"A consultant is a person who borrows your watch, tells you what time it is, pockets the watch, and sends you a bill for it.",
			"When you do not know what you are doing, do it neatly.",
			"It's your right to be stupid, but it doesn't mean you should be.",
			"The only way to get rid of corruption in high places is to get rid of high places.",
			"It's better to be looked over, than overlooked",
			"To be good is noble, but to teach others how to be good is nobler- and less trouble",
			"Courage is almost a contradiction in terms. It means a strong desire to live taking on the form of a readiness to die.",
			"You have to run as fast as you can just to stay where you are. If you want to get anywhere, you'll have to run much faster.",
			"The sooner you fall behind, the more time you'll have to catch up.",
			"Some have morals, some don't, most simply ignore them.",
			"No amount of advance planning will ever replace dumb luck.",
			"A little inaccuracy sometimes saves a ton of explanation.",
			"Opportunity only knocks once (if at all).",
			"It's not the people who are in prison that worry me. It's the people who aren't.",
			"In literature as in love, we are astonished at what is chosen by others.",
			"There are three ways to make money. You can inherit it. You can marry it. You can steal it.",
			"An author is a fool who, not content with boring those he lives with, insists on boring future generations.",
			"A diplomat is someone who can tell you to go to hell in such a way that you will look forward to the trip.",
			"Artificial Intelligence usually beats real stupidity.",
			"Not one shred of evidence supports the notion that life is serious.",
			"The moral sense enables one to perceive morality- and avoid it; the immoral sense enables one to perceive immorality- and enjoy it",
			"Most of our lives are about proving something, either to ourselves or to someone else.",
			"Always keep a record of data - it indicates you've been working.",
			"Truth is stranger than fiction; fiction is obliged to stick to possibilities, truth isn't",
			"A lot of people become pessimists from financing optimists.",
			"There's always something about your success that displeases even your best friends",
			"A candidate is a person who gets money from the rich and votes from the poor to protect them from each other.",
			"Friends may come and go, but enemies accumulate.",
			"The whole of science is nothing more than a refinement of everyday thinking",
			"Once a job is fouled up, anything done to improve it only makes it worse.",
			"Principles have no real force except when one is well fed",
			"The reason we are so pleased to find other people's secrets is that it distracts public attention from our own",
			"The older you get, the better you realize you were.",
			"Problems that go away by themselves, come back by themselves.",
			"Put all your eggs in one basket- and watch the basket",
			"Never wrestle a pig. You both get dirty and the pig likes it.",
			"Give a man a match, and he'll be warm for a minute, but set him on fire, and he'll be warm for the rest of his life.",
			"If pro is opposite of con, then what is the opposite of progress?,",
			"War doesn't determine who's right. War determines who's left.",
			"You can't be late until you show up.",
			"The real trouble with reality is that there's no background music.",
			"Going to church doesn't make you a Christian any more than standing in a garage makes you a car.",
			"Sarcasm helps keep you from telling people what you really think of them.",
			"Parents spend the first part of our lives teaching us to walk and talk, and the rest of it telling us to sit down and shut up.",
			"The secret to creativity is knowing how to hide your sources.",
			"Optimism: Waiting for a ship to come in when you haven't sent one out.",
			"You know your god is man-made when he hates all the same people you do.",
			"Knowledge is realizing that the street is one-way, wisdom is looking both directions anyway.",
			"If you think things can't get worse it's probably only because you lack sufficient imagination.",
			"Never run with scissors!,",
			"Always remember you're unique, just like everyone else.",
			"The early bird gets the worm, but the second mouse gets the cheese.",
			"Knowledge speaks, but wisdom listens.",
			"Never underestimate the power of stupid people in large groups.",
			"The only way to get rid of temptation is to yield to it.",
			"Once the toothpaste is out of the tube, it's hard to get it back in.",
			"In the end, it's not the years in your life that count, it's the life in your years.",
			"Make it idiot proof and someone will make a better idiot."
		);
	}
}
?>
